GET http://localhost:8080/api/registrationwithmessage/start/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/registrationwithmessage/confirm/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/registrationwithmessage/fail/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/registration/start/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/registration/confirm/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/registration/confirmmsg/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/registration/fail/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/api/status
Accept: */*
Cache-Control: no-cache

###