server:
  port: 8080

spring:
  profiles:
    active: development

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      ddl-auto: create
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 1234
      configuration:
        maximum-pool-size: 30

    camunda:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/camunda
      username: postgres
      password: 1234
      configuration:
        maximum-pool-size: 30

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks

